import { initSentry, instrumentMcpCall, Sentry } from "./sentry.ts";
initSentry();

import { Hyper, ok, route } from "@hyper/core";
import { hyperLog } from "@hyper/log";
import { corsPlugin } from "@hyper/cors";
import { authJwtPlugin } from "@hyper/auth-jwt";
import { rateLimit } from "@hyper/rate-limit";
import { compress } from "@hyper/compress";
import { idempotency } from "@hyper/idempotency";
import { openapiPlugin } from "@hyper/openapi";
import { zodConverter } from "@hyper/openapi-zod";
import { mcpServer } from "@hyper/mcp";
import { z } from "zod";

async function signJwt(
  payload: Record<string, unknown>,
  secret: string,
  opts: { expiresIn?: string } = {},
): Promise<string> {
  const header = btoa(JSON.stringify({ alg: "HS256", typ: "JWT" }))
    .replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  const now = Math.floor(Date.now() / 1000);
  const ttlSeconds = opts.expiresIn === "30d" ? 30 * 86400 : 86400;
  const body = { ...payload, iat: now, exp: now + ttlSeconds };
  const payloadB64 = btoa(JSON.stringify(body))
    .replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  const key = await crypto.subtle.importKey(
    "raw", new TextEncoder().encode(secret),
    { name: "HMAC", hash: "SHA-256" }, false, ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(`${header}.${payloadB64}`));
  const sigB64 = btoa(String.fromCharCode(...new Uint8Array(sig)))
    .replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
  return `${header}.${payloadB64}.${sigB64}`;
}

import markets from "./routes/markets.ts";
import quote from "./routes/quote.ts";
import trade from "./routes/trade.ts";
import positions from "./routes/positions.ts";
import spot from "./routes/spot.ts";
import lending from "./routes/lending.ts";
import leaderboard from "./routes/leaderboard.ts";
import reputation from "./routes/reputation.ts";
import ghost from "./routes/ghost.ts";
import bonds from "./routes/bonds.ts";
import copyTrading from "./routes/copy-trading.ts";
import stream from "./routes/stream.ts";

const llmsTxt = `# BUFI HYPER — Trading Infrastructure for AI Agents

> Forex perpetual futures, spot FX, and lending/borrowing on Arc (Circle L1)
> MCP-native. 2-call trading. Sub-second settlement. Up to 50x leverage.

## Quick Trade (2 calls, <3 seconds)
1. post__api_trade_prepare(symbol="EURC/USDC", side="long", sizeUsdc="5", leverage=2, trader="0x...")
   → returns { quote, order: { digest, typedData }, costEstimate }
2. Sign the digest with your wallet, then:
   post__api_trade_execute(symbol, trader, side, sizeUsdc, leverage, deadline, nonce, signature)
   → returns { intent, streamUrl }

## Quick Close (2 calls)
1. post__api_close_prepare(symbol="EURC/USDC", side="long", sizeUsdc="5", trader="0x...")
   → returns { order: { digest, typedData, reduceOnly: true } }
2. post__api_trade_execute(..., reduceOnly=true, signature)

## Spot Buy (2 calls)
1. post__api_spot_quote(symbol="EURC", amountUsdc="100")
   → returns { price, routeId }
2. post__api_spot_buy(symbol="EURC", trader="0x...", amountInAtomic, minAmountOutAtomic)
   → returns { digest, typedData }

## Supply & Earn Yield
1. get__api_lending_markets → see APYs
2. post__api_lending_supply(marketId, supplier="0x...", amount="100")
   → returns { action: "supply", market, deadline, nonce }

## Borrow Against Collateral
1. post__api_lending_borrow_preview(marketId, collateralAmount, borrowAmount) → check health factor
2. post__api_lending_borrow(marketId, borrower="0x...", borrowAmount, collateralAmount)

## Markets
- Perps: EURC/USDC, tJPYC/USDC, MXNB/USDC, CIRBTC/USDC, AUDF/USDC
- Up to 50x leverage, EIP-712 signed intents, Pyth oracle prices
- Spot: EURC, JPYC, MXNB (buy with USDC)
- Lending: supply USDC to earn yield, borrow FX tokens against collateral

## Defaults (omit unless overriding)
- chainId: 5042002 (Arc Testnet — only chain, never specify)
- orderType: "market" (default)
- leverage: 1 (default)
- ttl: 3600 seconds (1 hour deadline)
- reduceOnly: false
- Nonce and deadline: auto-generated by prepare tools

## Human-Readable Inputs
- Use symbol ("EURC/USDC") not marketId ("0x565a...")
- Use sizeUsdc ("5") not sizeDelta ("5000000")
- Use side ("long"/"short") not direction flags
- The MCP handles all conversions internally

## Pre-Flight Cost Check
post__api_cost(symbol, side, sizeUsdc, leverage)
→ { margin, fee, x402Fee, gasCost, total }

## Common Errors & Recovery
- "Unknown symbol" → use get__api_markets to see valid symbols
- "nonce already used" → retry (nonce is auto-generated)
- "wallet session required" → sign session typed-data headers
- "insufficient margin" → reduce sizeUsdc or leverage

## Agent Capabilities
Read (free): markets, quotes, positions, funding rates, lending APYs, leaderboard, reputation
Trade (x402 $0.001-$0.005): perp open/close, spot buy, supply, borrow, repay, withdraw

## ERC-8004 Agent Identity (Arc Testnet)
- IdentityRegistry: 0x8004A818BFB912233c491871b3d84c89A494BD9e
- ReputationRegistry: 0x8004B663056A597Dffe9eCcC1965A193B7388713
- ValidationRegistry: 0x8004Cb1BF31DAf7788923b405b754f57acEB4272
- Score: 0-100 from peer ratings (1-5 stars × 20)
- Every trader gets an onchain identity NFT

## Connect
- MCP: http://localhost:4002/mcp
- OpenAPI: http://localhost:4002/openapi.json
- Install: claude mcp add --transport http bufi-hyper http://localhost:4002/mcp

## Authentication
- Open mode (default): no auth required — all tools accessible (hackathon/testnet)
- JWT mode: set BUFI_JWT_SECRET, agents authenticate via Authorization: Bearer <token>
  - Token payload: { sub: "0xwalletAddress", scope: "trade read" }
  - Issue tokens scoped to wallet address — no session signatures needed
- Rate limit: 120 requests/minute per IP (standard RateLimit-* headers)

## Settlement
- Chain: Arc Testnet (chainId 5042002, sub-second finality)
- Gas: ~$0.01 USDC (USDC is native gas token)
- Oracle: Pyth Network (real-time forex feeds)
- Wallet: Circle Agent Wallet (circle CLI) — supports ERC-1271
`;

const tokenRoute = route
  .post("/auth/token")
  .body(
    z.object({
      address: z.string().regex(/^0x[0-9a-fA-F]{40}$/),
      scope: z.string().default("read trade"),
    }),
  )
  .meta({
    mcp: {
      title: "Issue API Key",
      description:
        "Issue a JWT API key for an agent wallet. The token authenticates all subsequent MCP calls — no session signatures needed. Scope: 'read' (free tools) or 'read trade' (all tools).",
    },
  })
  .handle(async ({ body }) => {
    const secret = process.env.BUFI_JWT_SECRET ?? process.env.JWT_SECRET;
    if (!secret) {
      return ok({
        mode: "open",
        note: "No JWT secret configured — all tools are accessible without auth (testnet mode).",
      });
    }
    const token = await signJwt(
      { sub: body.address, scope: body.scope },
      secret,
      { expiresIn: "30d" },
    );
    return ok({
      token,
      address: body.address,
      scope: body.scope,
      expiresIn: "30d",
      usage: `Authorization: Bearer ${token}`,
    });
  });

const llmsRoute = route.get("/llms.txt").handle(() => {
  return new Response(llmsTxt, {
    headers: { "content-type": "text/plain; charset=utf-8" },
  });
});

const health = route.get("/health").handle(() => ok({ ok: true, ts: Date.now() }));

const jwtSecret = process.env.BUFI_JWT_SECRET ?? process.env.JWT_SECRET;

const hyper = new Hyper()
  .use(hyperLog({ service: "bufi-hyper" }))
  .use(corsPlugin({ origin: "*", allowAnyOrigin: true }))
  .use(compress())
  .use(rateLimit({ limit: 120, window: "1m" }))
  .use(idempotency())
  .use(openapiPlugin({ converters: [zodConverter] }))
  .use([health, llmsRoute, tokenRoute])
  .use(markets)
  .use(quote)
  .use(trade)
  .use(positions)
  .use(spot)
  .use(lending)
  .use(leaderboard)
  .use(reputation)
  .use(ghost)
  .use(bonds)
  .use(copyTrading)
  .use(stream);

// JWT auth is opt-in: when BUFI_JWT_SECRET is set, agents authenticate
// via `Authorization: Bearer <token>` and get ctx.user with { sub, scope }.
// When unset, all routes are open (hackathon/testnet mode).
if (jwtSecret) {
  hyper.use(authJwtPlugin({ secret: jwtSecret, allowShortSecret: true }));
}

const port = Number(process.env.PORT ?? 4002);

const baseUrl = process.env.BUFI_MCP_URL ?? `http://localhost:${port}`;

const hyperApp = hyper.build();
const mcp = mcpServer(hyperApp);

const mcpLandingPage = {
  endpoint: `${baseUrl}/mcp`,
  protocol: "json-rpc-2.0",
  methods: ["initialize", "tools/list", "tools/call"],
  tools: mcp.listTools(),
  llmsTxt: `${baseUrl}/llms.txt`,
  openapi: `${baseUrl}/openapi.json`,
  snippet: {
    "claude-code": `claude mcp add --transport http bufi-hyper ${baseUrl}/mcp`,
    ".mcp.json": {
      mcpServers: {
        "bufi-hyper": { type: "url", url: `${baseUrl}/mcp` },
      },
    },
    "cursor / windsurf": {
      mcpServers: {
        "bufi-hyper": {
          command: "npx",
          args: ["-y", "mcp-remote", `${baseUrl}/mcp`, "--allow-http"],
        },
      },
    },
  },
};

export default {
  port,
  async fetch(req: Request) {
    const url = new URL(req.url);

    if (url.pathname === "/" && req.method === "GET") {
      return new Response(JSON.stringify({
        name: "BUFI HYPER",
        description: "Trading infrastructure for AI agents — forex perps, spot FX, lending, privacy pools on Arc",
        mcp: `${baseUrl}/mcp`,
        llmsTxt: `${baseUrl}/llms.txt`,
        openapi: `${baseUrl}/openapi.json`,
        health: `${baseUrl}/health`,
        tools: mcp.listTools().length,
        connect: `claude mcp add --transport http bufi-hyper ${baseUrl}/mcp`,
      }, null, 2), { headers: { "content-type": "application/json" } });
    }

    if (url.pathname === "/openapi.json" && req.method === "GET") {
      const spec = hyperApp.toOpenAPI?.() ?? { openapi: "3.1.0", info: { title: "BUFI HYPER MCP", version: "0.1.0" }, paths: {} };
      return new Response(JSON.stringify(spec, null, 2), { headers: { "content-type": "application/json" } });
    }

    if (url.pathname === "/mcp" || url.pathname.startsWith("/mcp/")) {
      if (req.method === "GET") {
        return new Response(JSON.stringify(mcpLandingPage, null, 2), {
          headers: { "content-type": "application/json" },
        });
      }
      let toolName = "unknown";
      try {
        const cloned = req.clone();
        const body = await cloned.json().catch(() => ({})) as { method?: string; params?: { name?: string } };
        if (body.method === "tools/call" && body.params?.name) {
          toolName = body.params.name;
        }
      } catch {}
      return instrumentMcpCall(toolName, null, () => mcp.handle(req));
    }
    return Sentry.withIsolationScope(() => hyperApp.fetch(req));
  },
};

setTimeout(async () => {
  const { livePerpsMarkets } = await import("@bufi/perps");
  const { perpsService } = await import("./services.ts");
  const markets = livePerpsMarkets(5042002);
  for (const m of markets.slice(0, 2)) {
    await perpsService.quote({ chainId: 5042002, marketId: m.marketId, side: "long", sizeUsdc: "1", sizeDelta: "1000000", leverage: 1 }).catch(() => {});
  }
  console.log(`  Oracle warmed for ${Math.min(2, markets.length)} markets`);
}, 100);

console.log(`BUFI HYPER MCP Gateway listening on :${port}`);
console.log(`  MCP:     http://localhost:${port}/mcp`);
console.log(`  OpenAPI: http://localhost:${port}/openapi.json`);
console.log(`  llms:    http://localhost:${port}/llms.txt`);
