// Kawaii Punk item metadata loader — the client/server bridge over item-map.json
// (generated by scripts/gen-kawaii-item-map.mjs). One lookup ties an asset to
// its display name, per-item description, rarity, and its two assets:
//   - menu : the big product-shot PNG shown in the picker
//   - nft  : the position-correct layer that composites into the minted Punk
//            (falls back to `menu` until per-item NFT variants are exported)
//
// itemMeta() always returns a value: unknown assets get a sensible fallback
// derived from the filename, so new drops render before the map is regenerated.
import map from "./item-map.json";

export type Rarity = "Legendary" | "Rare" | "Common";
/** Mythical-creature origin (bases): where the legend is from + its reach. */
export type Origin = {
  creature: string;
  country: string;
  flag: string; // flag emoji (🛸 for global UFO lore)
  scope: "country" | "regional" | "global";
  region?: string; // shown when scope is regional/global (e.g. "LATAM")
};
export type ItemMeta = {
  name: string;
  desc: string;
  rarity: Rarity;
  menu: string; // filename used for picker thumbnails
  nft: string; // filename composited into the avatar / minted NFT
  nftReady: boolean; // true once a real (smaller, positioned) nft variant exists
  origin?: Origin; // present on mythical-creature bases
};

type LocaleStrings = { name?: string; desc?: string };
type RawItem = Partial<ItemMeta> & { menu?: string; i18n?: Record<string, LocaleStrings> };
const ITEMS = (map as { items: Record<string, RawItem> }).items;

function fileLabel(file: string): string {
  let b = file.replace(/\.png$/i, "").replace(/[_-]+/g, " ").trim();
  b = b.replace(/^base\s+/i, "").replace(/^neutral\s+/i, "");
  return b.charAt(0).toUpperCase() + b.slice(1);
}
function rarityOf(file: string): Rarity {
  return /legendary/i.test(file) ? "Legendary" : /rare/i.test(file) ? "Rare" : "Common";
}

/** Metadata for a (category, filename) pair. Always resolves (map → fallback).
 *  Pass `locale` to get the translated name/desc (falls back to English). */
export function itemMeta(cat: string, file: string, locale?: string): ItemMeta {
  const hit = ITEMS[`${cat}/${file}`];
  if (hit) {
    const loc = locale && locale !== "en" ? hit.i18n?.[locale] : undefined;
    return {
      name: loc?.name ?? hit.name ?? fileLabel(file),
      desc: loc?.desc ?? hit.desc ?? "",
      rarity: hit.rarity ?? rarityOf(file),
      menu: hit.menu ?? file,
      nft: hit.nft ?? hit.menu ?? file,
      nftReady: hit.nftReady ?? false,
      ...(hit.origin ? { origin: hit.origin } : {}),
    };
  }
  const name = fileLabel(file);
  return { name, desc: "", rarity: rarityOf(file), menu: file, nft: file, nftReady: false };
}

/** The filename that should composite into the avatar / NFT for this item. */
export const nftFileOf = (cat: string, file: string): string => itemMeta(cat, file).nft;
